# Inference

In [79]:
import pandas as pd
import numpy as np
import pickle
import dill
from function_label import label_encode_column


## Inference with single random data.

In [80]:
with open('best_model_dt.pkl', 'rb') as file_1:
  model3 = pickle.load(file_1)

In [81]:
data = {
    'Age':26,
    'Gender':'Male',
    'Item Purchased':'Shoes',
    'Category': 'Footwear',
    'Purchase Amount': 5,
    'Size':'S',
    'Color':'Black',
    'Season':'Summer',
    'Review Rating':4.2,
    'Shipping Type':'Next Day Air',
    'Discount Applied': 'Yes',
    'Promo Code Used':'Yes',
    'Previous Purchases':20,
    'Payment Method':'Credit Card',
    'Frequency of Purchases':'Annually'
}

data = pd.DataFrame([data])
data

Age Gender Item Purchased  Category  Purchase Amount Size  Color  Season  \
0   26   Male          Shoes  Footwear                5    S  Black  Summer   

   Review Rating Shipping Type Discount Applied Promo Code Used  \
0            4.2  Next Day Air              Yes             Yes   

   Previous Purchases Payment Method Frequency of Purchases  
0                  20    Credit Card               Annually

In [82]:
y_pred = model3.predict(data)
y_pred

array([0])

The Result are 0 or 'Not Subscribe'

## Inference with actual data from dataset

In [83]:
dumm = pd.read_csv("shopping_behavior_updated.csv")

In [84]:
dumm['Subscription Status'].unique()

array(['Yes', 'No'], dtype=object)

In [85]:
dumm.drop(['Customer ID'], axis=1, inplace=True)
dumm.drop(['Location'], axis=1, inplace=True)
dumm = dumm.rename(columns={'Purchase Amount (USD)': 'Purchase Amount'})

In [86]:
subs_yes = dumm[dumm['Subscription Status']== 'Yes']

In [87]:
subs_no = dumm[dumm['Subscription Status']== 'No']

### Predict with original data data where Subs Status == Yes.

In [88]:
y_pred = model3.predict(subs_yes)
np.set_printoptions(threshold=np.inf)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### Predict with original data where Subs Status == No.

In [89]:
y_pred = model3.predict(subs_no)
np.set_printoptions(threshold=np.inf)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,